add_subdirectory(demo)
add_subdirectory(rotating_blocks)
add_subdirectory(connected_particles)
add_subdirectory(audio_demo)
add_subdirectory(audio_playground)
add_subdirectory(gravitas)
add_subdirectory(gravitas_ai)
add_subdirectory(molds)
add_subdirectory(steering_behavior)
add_subdirectory(breakout)
add_subdirectory(thetower)
add_subdirectory(predator_and_prey)
add_subdirectory(text_wrapping)
add_subdirectory(furier_series)
add_subdirectory(lkas)
add_subdirectory(custom_effects)
