add_subdirectory(animation_test)
add_subdirectory(audio_visualizer)
add_subdirectory(bubble_words)
add_subdirectory(disco_grid)
add_subdirectory(interactive_display)
add_subdirectory(interactive_grid)
add_subdirectory(interactive_text)
add_subdirectory(jelly_tentacles)
add_subdirectory(rotating_typography)
add_subdirectory(text_to_points)
